services:
  inference:
    build:
      context: .
      dockerfile: inference/Dockerfile
    image: image-caption-api:latest
    container_name: image-caption-api
    ports:
      - "8000:8000"
    volumes:
      - ./shared/artifacts:/app/artifacts
    profiles: ["inference"]
